# Config file for automatic testing at travis-ci.org
language: python
python:
{%- if cookiecutter.Python_version == 'Python 2 and 3' or cookiecutter.Python_version == 'Python 2' %}
  - "2.7"
{%- endif %}
{%- if cookiecutter.Python_version == 'Python 3' or cookiecutter.Python_version == 'Python 2 and 3' %}
  - "3.4"
  - "3.5"
  - "3.6"
{%- endif %}

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: python setup.py test

{%- if cookiecutter.pypi_user != 'no_pypi_travis_deployment' %}
# deploy automatically to pypi when a release is made
deploy:
  provider: pypi
  user: {{ cookiecutter.pypi_user }}
  password:
    secure: FIXME; see README for more info
  on:
    tags: true
    branch: master
{%- endif %}
